name: Docker Image CI

on: 
  push:
    branches: 
      - master
  
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag myates/basic-computer:$(date +%s)
    - name: test the docker image
      run: docker run -e CI=true myates/basic-computer:latest
